"""creates join tables for movement and journal entries

Revision ID: 0bcd6dc0cd05
Revises: f37d066ec48b
Create Date: 2026-01-19 15:10:11.259856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bcd6dc0cd05'
down_revision = 'f37d066ec48b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_entry_movements',
    sa.Column('journal_entry_id', sa.Integer(), nullable=False),
    sa.Column('movement_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['movement_id'], ['movements.id'], ),
    sa.PrimaryKeyConstraint('journal_entry_id', 'movement_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journal_entry_movements')
    # ### end Alembic commands ###
