"""fix journal entry

Revision ID: 22144e538551
Revises: b20b0987428a
Create Date: 2026-01-19 17:00:23.333405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22144e538551'
down_revision = 'b20b0987428a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
        batch_op.alter_column('img_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('datetime')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datetime', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('img_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('created_at')

    op.drop_table('users')
    # ### end Alembic commands ###
