"""initial reset

Revision ID: 884398973e31
Revises: 
Create Date: 2026-01-20 11:33:53.248944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '884398973e31'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mood',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('slug', sa.String(length=30), nullable=False),
    sa.Column('valence', sa.String(length=30), nullable=False),
    sa.Column('energy', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('slug', sa.String(length=30), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('is_outdoor', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal_entry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reflection', sa.String(length=511), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('img_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('je_mood_after_association',
    sa.Column('je_id', sa.Integer(), nullable=False),
    sa.Column('mood_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['je_id'], ['journal_entry.id'], ),
    sa.ForeignKeyConstraint(['mood_id'], ['mood.id'], ),
    sa.PrimaryKeyConstraint('je_id', 'mood_id')
    )
    op.create_table('je_mood_before_association',
    sa.Column('je_id', sa.Integer(), nullable=False),
    sa.Column('mood_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['je_id'], ['journal_entry.id'], ),
    sa.ForeignKeyConstraint(['mood_id'], ['mood.id'], ),
    sa.PrimaryKeyConstraint('je_id', 'mood_id')
    )
    op.create_table('je_movement_association',
    sa.Column('je_id', sa.Integer(), nullable=False),
    sa.Column('movement_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['je_id'], ['journal_entry.id'], ),
    sa.ForeignKeyConstraint(['movement_id'], ['movement.id'], ),
    sa.PrimaryKeyConstraint('je_id', 'movement_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('je_movement_association')
    op.drop_table('je_mood_before_association')
    op.drop_table('je_mood_after_association')
    op.drop_table('journal_entry')
    op.drop_table('user')
    op.drop_table('movement')
    op.drop_table('mood')
    # ### end Alembic commands ###
