"""establishes all columns and relationships

Revision ID: b20b0987428a
Revises: e04bf0b0b6b7
Create Date: 2026-01-19 16:49:05.450488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b20b0987428a'
down_revision = 'e04bf0b0b6b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.alter_column('img_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('datetime',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('datetime',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
        batch_op.alter_column('img_path',
               existing_type=sa.VARCHAR(),
               nullable=False)

    op.drop_table('users')
    # ### end Alembic commands ###
