"""creates join tables for mood before, mood after and je

Revision ID: e04bf0b0b6b7
Revises: 0bcd6dc0cd05
Create Date: 2026-01-19 15:15:54.895912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e04bf0b0b6b7'
down_revision = '0bcd6dc0cd05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_entry_moods_after',
    sa.Column('journal_entry_id', sa.Integer(), nullable=False),
    sa.Column('mood_after_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['mood_after_id'], ['moods.id'], ),
    sa.PrimaryKeyConstraint('journal_entry_id', 'mood_after_id')
    )
    op.create_table('journal_entry_moods_before',
    sa.Column('journal_entry_id', sa.Integer(), nullable=False),
    sa.Column('mood_before_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['mood_before_id'], ['moods.id'], ),
    sa.PrimaryKeyConstraint('journal_entry_id', 'mood_before_id')
    )
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reflection', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('img_path', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('datetime', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_column('datetime')
        batch_op.drop_column('img_path')
        batch_op.drop_column('user_id')
        batch_op.drop_column('reflection')

    op.drop_table('journal_entry_moods_before')
    op.drop_table('journal_entry_moods_after')
    # ### end Alembic commands ###
